export const NETWORK_ERROR = 'No Network.';
export const DATA_NOT_FOUND = 'Data not found.';
export const PLEASE_ENTER_PHONE = 'Please enter mobile number.';
export const PLEASE_CREATE_NUMBER = 'your number is not found.';
export const PLEASE_CREATE_SIGNUP = 'create a new account.';

export const PLEASE_ENTER_NAME = 'Please enter name.';
export const PLEASE_ENTER_ADDRESS = 'Please enter address.';
export const PLEASE_ENTER_FIRST_NAME = 'Please enter first name.';
export const PLEASE_ENTER_LAST_NAME = 'Please enter last name.';
export const PLEASE_ENTER_COMPANY = 'Please enter company.';
export const PLEASE_ENTER_DESIGNATION = 'Please enter designation.';
export const PLEASE_ENTER_EMAIL = 'Please enter email.';
export const PLEASE_ENTER_MESSAGE = 'Please enter message.';
export const PLEASE_ENTER_CITY = 'Please enter city.';
export const PLEASE_ENTER_ZIP = 'Please enter zip code.';
export const PLEASE_ENTER_OCCUPATION = 'Please enter occupation.';
export const PLEASE_ENTER_OWN_CAR1 = 'Please enter own car 1.';
export const PLEASE_ENTER_OWN_CAR2 = 'Please enter own car 2.';
